import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
const root = new URL("../", import.meta.url).pathname;
const read = (path) => readFileSync(join(root, path), "utf8");
const migration = read("supabase/migrations/20260922203000_deck_studio_project_pulse.sql");
const page = read("src/pages/studio/projects/[id]/pulse/index.astro");
const create = read("src/pages/api/studio/projects/[id]/pulse.ts");
const withdraw = read("src/pages/api/studio/pulse/[id].ts");
const exporter = read("src/pages/api/studio/projects/[id]/export/[format].ts");
assert.match(migration, /unique \(owner_id, billing_month\)/);
assert.match(migration, /access_expires_at > new\.accepted_at \+ interval '14 days'/);
assert.match(migration, /Assigned reviewers can read active Project Pulse requests/);
assert.match(migration, /consent_withdrawn_at is null/);
assert.match(migration, /cardinality\(observations\) <= 3/);
assert.match(migration, /Creators may only withdraw Project Pulse consent/);
assert.match(migration, /No detailed manuscript editing, production verification or automatic rewriting/);
assert.match(page, /one priority question per billing month/i);
assert.match(page, /up to three observations/i);
assert.match(page, /Withdraw consent/);
assert.match(page, /Next useful step/);
assert.match(create, /form\.get\("consent"\) !== "on"/);
assert.match(withdraw, /consent_withdrawn_at/);
assert.match(exporter, /getStudioProjectWorkspace/);
assert.match(exporter, /getStudioJournalEntries/);
assert.match(exporter, /Cache-Control": "private, no-store"/);
assert.match(exporter, /Content-Disposition/);
for (const source of [migration,page,create,withdraw,exporter]) assert.doesNotMatch(source, /repeating-card-meanings|community_posts|stripe/i);
console.log("Deck Creator Studio Project Pulse and export contracts: passed");
