import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
const root = new URL("../", import.meta.url).pathname;
const read = (path) => readFileSync(join(root, path), "utf8");
const billing = read("src/lib/studio/billing.ts");
const access = read("src/lib/studio/access.ts");
const migration = read("supabase/migrations/20260922224500_deck_studio_commercial_access.sql");
const offer = read("src/pages/tools/deck-creator-studio/index.astro");
const checkout = read("src/pages/api/studio/billing/checkout.ts");
const webhook = read("src/pages/api/studio/billing/webhook.ts");
const portal = read("src/pages/api/studio/billing/portal.ts");
const onboarding = read("src/pages/api/studio/onboarding.ts");
const grants = read("src/pages/api/studio/billing/grants.ts");
const capacity = read("src/pages/api/studio/billing/capacity.ts");
const analytics = read("src/pages/api/studio/analytics.ts");

assert.match(billing, /amountUsd:\s*197/);
assert.match(billing, /amountUsd:\s*597/);
assert.match(billing, /amountUsd:\s*1495/);
assert.match(billing, /minimumPayments:\s*3/);
assert.match(billing, /startsWith\("sk_test_"\)/);
assert.match(billing, /STUDIO_READ_ONLY_RETENTION_DAYS/);
assert.match(billing, /entitlementStatusForSubscription/);
assert.match(migration, /\('circle', 10\)/);
assert.match(migration, /studio_reserve_checkout/);
assert.match(migration, /access_mode in \('write','read_only'\)/);
assert.match(migration, /public\.studio_has_write_access\(\)/);
assert.match(offer, /Creators? retain|You retain authorship/i);
assert.match(offer, /does not include unlimited manuscript rewriting/i);
assert.match(checkout, /mode:\s*"subscription"/);
assert.match(checkout, /studio_reserve_checkout/);
assert.match(checkout, /minimum_payments/);
assert.match(webhook, /event\.livemode/);
assert.match(webhook, /checkout\.session\.completed/);
assert.match(webhook, /customer\.subscription\.deleted/);
assert.match(webhook, /invoice\.payment_failed/);
assert.match(webhook, /invoice\.paid/);
assert.match(webhook, /cancel_at_period_end: true/);
assert.match(webhook, /idempotent:\s*true/);
assert.match(portal, /billingPortal\.sessions\.create/);
assert.match(onboarding, /onboarding_complete/);
assert.match(grants, /studio_entitlement_audit/);
assert.match(grants, /toISOString\(\)/);
assert.match(capacity, /capacity_limit/);
assert.match(analytics, /Analytics must never interrupt/);
assert.match(access, /read-only\. Exports remain available/);
for (const source of [billing, access, migration, offer, checkout, webhook, portal, onboarding, grants, capacity, analytics]) {
  assert.doesNotMatch(source, /sk_live_|STRIPE_SECRET_KEY(?!_)/);
  assert.doesNotMatch(source, /repeating-card-meanings|community_posts/i);
}
console.log("Deck Creator Studio commercial access contracts: passed");
