-- Seed three manually verified complimentary Ask Leilia testimonials.
-- Idempotent: fixed UUIDs with ON CONFLICT (id) DO NOTHING.
-- No request_id, review tokens, Stripe links, or paid-reading verification claims.

insert into public.ask_leilia_reviews (
  id,
  request_id,
  review_token_id,
  reviewer_email,
  display_name,
  reading_type,
  rating,
  title,
  body_original,
  body_public,
  consent_publish,
  consent_marketing,
  verification_status,
  moderation_status,
  is_featured,
  submitted_at,
  approved_at,
  approved_by,
  updated_at
)
values
  (
    'c5e1f8a0-0708-4111-8b25-00a5c1e11001',
    null,
    null,
    'sarah.complimentary.20260708@example.invalid',
    'Sarah',
    'complimentary',
    5,
    'Clearer than my own perspective',
    'Leigh helped me step back from my own emotional bias and see the situation more clearly. Her interpretation was thoughtful, balanced and genuinely useful, especially because I tend to view my own readings more negatively.',
    'Leigh helped me step back from my own emotional bias and see the situation more clearly. Her interpretation was thoughtful, balanced and genuinely useful, especially because I tend to view my own readings more negatively.',
    true,
    false,
    'manually_verified',
    'approved',
    true,
    '2026-07-08T12:00:00+00:00',
    '2026-07-08T12:00:00+00:00',
    null,
    '2026-07-08T12:00:00+00:00'
  ),
  (
    'c5e1f8a0-0710-4111-8b25-00a5c1e11002',
    null,
    null,
    'anonymous.complimentary.20260710@example.invalid',
    'Anonymous',
    'complimentary',
    5,
    'Insightful and easy to understand',
    'I loved Leigh''s interpretation. It was insightful, thoughtful and gave me a fresh way to understand both the cards and the situation.',
    'I loved Leigh''s interpretation. It was insightful, thoughtful and gave me a fresh way to understand both the cards and the situation.',
    true,
    false,
    'manually_verified',
    'approved',
    false,
    '2026-07-10T12:00:00+00:00',
    '2026-07-10T12:00:00+00:00',
    null,
    '2026-07-10T12:00:00+00:00'
  ),
  (
    'c5e1f8a0-0712-4111-8b25-00a5c1e11003',
    null,
    null,
    'anonymous.complimentary.20260712@example.invalid',
    'Anonymous',
    'complimentary',
    5,
    'A beautiful interpretation',
    'This was such a beautiful interpretation. It made sense immediately, and I especially appreciated the way Leigh explained how she was reading the cards, not just the conclusion she reached.',
    'This was such a beautiful interpretation. It made sense immediately, and I especially appreciated the way Leigh explained how she was reading the cards, not just the conclusion she reached.',
    true,
    false,
    'manually_verified',
    'approved',
    true,
    '2026-07-12T12:00:00+00:00',
    '2026-07-12T12:00:00+00:00',
    null,
    '2026-07-12T12:00:00+00:00'
  )
on conflict (id) do nothing;
